export default function Footer() {
  return (
    <div
      dangerouslySetInnerHTML={{
        __html: `<!-- FOOTER -->     <footer class="footer">       <div class="container">         <div class="footer-grid">           <div class="footer-brand">             <a href="#home" class="logo">               <span class="logo-mark">A</span>               <span class="logo-text">Apex<em>Coaching</em></span>             </a>             <p class="footer-tagline">               Empowering individuals to reach their highest potential through               expert, personalized coaching.             </p>             <div class="social-icons">               <a href="#" class="social-icon" aria-label="Twitter">𝕏</a>               <a href="#" class="social-icon" aria-label="LinkedIn">in</a>               <a href="#" class="social-icon" aria-label="Instagram">◎</a>               <a href="#" class="social-icon" aria-label="YouTube">▶</a>             </div>           </div>           <div class="footer-col">             <h4>Quick Links</h4>             <ul>               <li><a href="#home">Home</a></li>               <li><a href="#programs">Programs</a></li>               <li><a href="#coaches">Coaches</a></li>               <li><a href="#testimonials">Testimonials</a></li>               <li><a href="#contact">Contact</a></li>             </ul>           </div>           <div class="footer-col">             <h4>Programs</h4>             <ul>               <li><a href="#programs">Career Coaching</a></li>               <li><a href="#programs">Business Coaching</a></li>               <li><a href="#programs">Life Coaching</a></li>               <li><a href="#programs">Leadership Coaching</a></li>             </ul>           </div>           <div class="footer-col">             <h4>Company</h4>             <ul>               <li><a href="#">About Us</a></li>               <li><a href="#">Blog</a></li>               <li><a href="#">Careers</a></li>               <li><a href="#">Privacy Policy</a></li>               <li><a href="#">Terms of Service</a></li>             </ul>           </div>         </div>         <div class="footer-bottom">           <p>&copy; 2025 ApexCoaching. All rights reserved.</p>           <p>Designed with ♥ for growth-minded individuals</p>         </div>       </div>     </footer>`,
      }}
    />
  );
}
